listen_ip: 0.0.0.0
ports:
  - serial_device: /dev/ttyUSB0
    tcp_port: 5000
    baud_rate: 115200
  - serial_device: /dev/ttyUSB1
    tcp_port: 5001
    baud_rate: 9600
  - serial_device: /dev/ttyUSB2
    tcp_port: 5002
    baud_rate: 57600
